rkt = "/usr/bin/rkt"
image-prefix = "docker://"
default-interactive-cmd = "sh"

[environment]
# needed for per-application options --stdout, etc
# as per https://github.com/rkt/rkt/issues/3639
RKT_EXPERIMENT_ATTACH = "true"

[options]
general = ["--insecure-options=image"]
run = ["--set-env=HOME=/home/{{.Username}}"]
# --stdout=stream ought to work, but doesn't
# see https://github.com/rkt/rkt/issues/3639
image = ["--user={{.Uid}}", "--group={{.Gid}}", "--stdout=log"]

[volume.home]
volume = "kind=host,source={{.HomeDir}}"
mount = "target=/home/{{.Username}}"

[volume.dataset]
volume = "kind=host,source=/dataset"
mount = "target=/dataset"

[volume.bifo]
volume = "kind=host,source=/bifo"
mount = "target=/bifo"

[volume.volume-config]
volume = "kind=empty,uid={{.Uid}},gid={{.Gid}}"

[volume.volume-data]
volume = "kind=empty,uid={{.Uid}},gid={{.Gid}}"
