rkt = "/usr/bin/rkt"
preserve-cwd = true
use-path = true
exec-slave-dir = "/usr/libexec/rktrunner"
default-interactive-cmd = "sh"

[environment]
# these are passed in a file, not on the command line
HOME = "/home/{{.Username}}"
http_proxy = "{{.http_proxy}}"
https_proxy = "{{.https_proxy}}"

[options.common]
general = ["--insecure-options=image"]
run = [
    "--net=host",
]
image = [
    "--user={{.Uid}}",
    "--group={{.Gid}}",
    "--seccomp", "mode=retain,@docker/default-whitelist,mbind",  # for Julia, see https://github.com/rkt/rkt/issues/3651
]

[options.batch]
run = [
    "--stage1-name=coreos.com/rkt/stage1-fly:1.25.0",
]

[auto-image-prefix]
"biocontainers/" = "docker://biocontainers/"

[volume.home]
volume = "kind=host,source={{.HomeDir}}"
mount = "target=/home/{{.Username}}"

[volume.dataset]
volume = "kind=host,source=/dataset"
mount = "target=/dataset"

[volume.bifo]
volume = "kind=host,source=/bifo"
mount = "target=/bifo"

[volume.volume-config]
volume = "kind=empty,uid={{.Uid}},gid={{.Gid}}"
on-request = true

[volume.volume-data]
volume = "kind=empty,uid={{.Uid}},gid={{.Gid}}"
on-request = true

#
# Aliases - keep alphabetical
#
# By convention, we append an underscore to the aliases for images
# which don't have a default executable.
#

[alias.blast_]
image = "quay.io/biocontainers/blast:2.6.0--boost1.61_0"
exec = ["/usr/local/bin/blastn","/usr/local/bin/blastp","/usr/local/bin/blastx","/usr/local/bin/tblastn","/usr/local/bin/tblastx"]

[alias.bwa_]
image = "quay.io/biocontainers/bwa:0.7.15--0"
exec = ["/usr/local/bin/bwa"]

[alias.julia_]
image = "docker://julia"
exec = ["/usr/local/julia/bin/julia"]

[alias.qiime_]
image = "quay.io/biocontainers/qiime:1.9.1--py27_0"

[alias.ruby_]
image = "docker://ruby"
exec = ["/usr/local/bin/ruby", "/usr/local/bin/irb"]
